# Generated by Django 6.1 on 2026-08-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trading name shown on documents', max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('business_identification_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='BIN (13-digit VAT registration)')),
                ('tax_identification_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN / e-TIN')),
                ('drug_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_license_expiry_date', models.DateField(blank=True, null=True)),
                ('trade_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('default_currency', models.CharField(default='BDT', max_length=10)),
                ('invoice_footer_note', models.TextField(blank=True, help_text='Terms or thank-you note printed at the foot of every invoice', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
                'db_table': 'company_profiles',
                'ordering': ['-is_active', '-id'],
            },
        ),
    ]
