# Generated by Django 6.1 on 2026-08-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0002_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bomheader',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='QA Head or Plant Manager who approved this formula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_boms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='finished_product',
            field=models.ForeignKey(help_text='Commercial pharmaceutical finished product', on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='bom',
            field=models.ForeignKey(help_text='Linked BOM Header master recipe', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.bomheader'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='material',
            field=models.ForeignKey(help_text='Raw drug API, excipient chemical, or packaging component', on_delete=django.db.models.deletion.PROTECT, related_name='bom_usages', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='finishedgoodstransfer',
            name='accounting_voucher',
            field=models.ForeignKey(blank=True, help_text='Double-entry Journal Voucher (JV) posted to General Ledger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_transfer_vouchers', to='accounting.voucher'),
        ),
        migrations.AddField(
            model_name='finishedgoodstransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finished_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finishedgoodstransfer',
            name='destination_warehouse',
            field=models.ForeignKey(help_text='Commercial finished goods central depot', on_delete=django.db.models.deletion.PROTECT, related_name='received_finished_transfers', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='finishedgoodstransfer',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_finished_goods', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='finishedgoodstransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Finished goods warehouse in-charge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_finished_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Storekeeper who dispensed and issued the material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_material_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='Production pharmacist who received the ingredients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_material_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='warehouse',
            field=models.ForeignKey(help_text='Source raw and packaging store', on_delete=django.db.models.deletion.PROTECT, related_name='issued_material_slips', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='materialissueitem',
            name='material_issue_slip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.materialissueslip'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='assigned_operators',
            field=models.ManyToManyField(blank=True, help_text='Machine technicians and operators assigned to this batch', related_name='operated_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='assigned_supervisor',
            field=models.ForeignKey(blank=True, help_text='Quality Pharmacist / Shift In-Charge supervising manufacturing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='bom',
            field=models.ForeignKey(help_text='Approved Master Formula Record (BOM) used for this batch', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.bomheader'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='destination_warehouse',
            field=models.ForeignKey(help_text='Finished goods depot where approved medicine will be transferred', on_delete=django.db.models.deletion.PROTECT, related_name='destination_batches', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='finished_product',
            field=models.ForeignKey(help_text='Commercial pharmaceutical medicine to be produced', on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='source_warehouse',
            field=models.ForeignKey(help_text='Raw material and packaging store from which ingredients are issued', on_delete=django.db.models.deletion.PROTECT, related_name='source_batches', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='batch',
            field=models.ForeignKey(help_text='Target production batch', on_delete=django.db.models.deletion.CASCADE, related_name='material_issue_slips', to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='finishedgoodstransfer',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods_transfers', to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='production_line',
            field=models.ForeignKey(help_text='Physical manufacturing line and cleanroom suite', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='production.productionline'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='production_plan',
            field=models.ForeignKey(blank=True, help_text='Master production schedule reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='production.productionplan'),
        ),
        migrations.AddField(
            model_name='productionstagelog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='productionstagelog',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Technician/Chemist who operated the machine or tested the stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_production_stages', to=settings.AUTH_USER_MODEL),
        ),
    ]
