# Generated by Django 6.1 on 2026-08-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0002_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_grns', to=settings.AUTH_USER_MODEL, verbose_name='QC / Manager Approved By'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grns', to=settings.AUTH_USER_MODEL, verbose_name='Received By'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='receiving_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_grns', to='inventory.warehouse', verbose_name='Receiving Warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='goods_received_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.goodsreceivednote', verbose_name='GRN Reference'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_received_items', to='inventory.product', verbose_name='Received Product'),
        ),
        migrations.AddField(
            model_name='lcdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_lc_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='lclandingcost',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_landed_costs', to=settings.AUTH_USER_MODEL, verbose_name='Finalized By'),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lcs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='issuing_bank_account',
            field=models.ForeignKey(help_text='Bank account head used to fund and open this LC', on_delete=django.db.models.deletion.PROTECT, related_name='issued_lcs', to='accounting.accounthead', verbose_name='Issuing Bank Ledger Account'),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='margin_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='margin_funded_lcs', to='accounting.voucher', verbose_name='LC Margin Accounting Voucher'),
        ),
        migrations.AddField(
            model_name='lclandingcost',
            name='letter_of_credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_cost', to='purchases.letterofcredit', verbose_name='Letter of Credit Reference'),
        ),
        migrations.AddField(
            model_name='lcdocument',
            name='letter_of_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchases.letterofcredit', verbose_name='Letter of Credit Reference'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='letter_of_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_received_notes', to='purchases.letterofcredit', verbose_name='Letter of Credit Reference'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_purchase_orders', to='inventory.warehouse', verbose_name='Destination Warehouse'),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_of_credit', to='purchases.purchaseorder', verbose_name='Purchase Order Reference'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_received_notes', to='purchases.purchaseorder', verbose_name='Purchase Order Reference'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(help_text='Active Pharmaceutical Ingredient (API), Excipient, or Packaging Material', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.product', verbose_name='Product / Raw Material'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='Purchase Order Reference'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_received_items', to='purchases.purchaseorderitem', verbose_name='Matched PO Item Line'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchases.supplier', verbose_name='Supplier / Vendor'),
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters_of_credit', to='purchases.supplier', verbose_name='Overseas Supplier / Beneficiary'),
        ),
    ]
