# Generated by Django 6.1 on 2026-08-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Draft', max_length=50),
        ),
    ]
