# Generated by Django 6.1 on 2026-08-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourallowance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
