# Generated by Django 6.1 on 2026-08-18 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role'),
        ('hr', '0008_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='current_approver_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AlterField(
            model_name='payrollapproval',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
