# Generated by Django 6.1 on 2026-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_payroll_current_approver_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='biometric_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_method',
            field=models.CharField(choices=[('GPS', 'GPS'), ('Biometric Fingerprint', 'Biometric Fingerprint'), ('Dual Verified (GPS + Fingerprint)', 'Dual Verified (GPS + Fingerprint)'), ('Manual Entry', 'Manual Entry')], default='GPS', max_length=50),
        ),
    ]
