# Generated by Django 6.1 on 2026-08-25 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_attendance_biometric_device_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('is_tracking_active', models.BooleanField(db_index=True, default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_current_locations',
            },
        ),
        migrations.CreateModel(
            name='UserLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy radius in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Movement speed in m/s', null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Device battery percentage', null=True)),
                ('is_mock_location', models.BooleanField(default=False, help_text='True if fake/mock GPS app detected')),
                ('recorded_at', models.DateTimeField(help_text='Device timestamp when GPS coordinate was captured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_location_logs',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='user_locati_user_id_43da95_idx')],
            },
        ),
    ]
