# Generated by Django 6.1 on 2026-08-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_usercurrentlocation_userlocationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrentlocation',
            name='location_name',
            field=models.CharField(blank=True, help_text='Human-readable reverse geocoded place name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlocationlog',
            name='location_name',
            field=models.CharField(blank=True, help_text='Human-readable reverse geocoded place name', max_length=255, null=True),
        ),
    ]
