# Generated by Django 6.1 on 2026-08-30 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='note',
            field=models.TextField(blank=True, help_text='Reason for the loan, agreed terms, or any administrative remarks', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, help_text="Fixed amount deducted from the employee's salary every month. Set by the admin.", max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('remaining_amount__gt', 0)), fields=('user',), name='unique_open_loan_per_user'),
        ),
    ]
