# Generated by Django 6.1 on 2026-08-30 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_loan_note_alter_loan_emi_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TAComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short stable identifier, e.g. TRANSPORT, MEAL, HOTEL', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TA Component',
                'verbose_name_plural': 'TA Components',
                'db_table': 'ta_components',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='daily_ta_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED. Superseded by per-employee, per-component rates in EmployeeTARate. Retained for historical reference only; payroll no longer reads this field.', max_digits=12),
        ),
        migrations.CreateModel(
            name='EmployeeTARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount earned per eligible working day for this component', max_digits=12)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_rates', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_rates', to='hr.tacomponent')),
            ],
            options={
                'verbose_name': 'Employee TA Rate',
                'verbose_name_plural': 'Employee TA Rates',
                'db_table': 'employee_ta_rates',
                'ordering': ['user', 'component', '-effective_from'],
                'unique_together': {('user', 'component', 'effective_from')},
            },
        ),
    ]
