# Generated by Django 6.1 on 2026-08-30 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('hr', '0015_seed_ta_components_and_migrate_daily_ta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('eligible_days', models.IntegerField(default=0, help_text='Days actually worked, excluding holidays, off-days, leave and absence')),
                ('total_daily_ta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tour_da', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowance_bill_vouchers', to='accounting.voucher')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allowance_bills', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_allowance_bills', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TA/DA Bill',
                'verbose_name_plural': 'TA/DA Bills',
                'db_table': 'allowance_bills',
                'ordering': ['-year', '-month', '-id'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AllowanceBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Daily TA Component', 'Daily TA Component'), ('Tour Allowance (DA)', 'Tour Allowance (DA)')], default='Daily TA Component', max_length=50)),
                ('days', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.allowancebill')),
                ('component', models.ForeignKey(blank=True, help_text='Set for daily TA lines; empty for tour lines', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='hr.tacomponent')),
                ('tour_allowance', models.ForeignKey(blank=True, help_text='Set for tour DA lines; empty for daily TA lines', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='hr.tourallowance')),
            ],
            options={
                'verbose_name': 'TA/DA Bill Line',
                'verbose_name_plural': 'TA/DA Bill Lines',
                'db_table': 'allowance_bill_lines',
                'ordering': ['source', 'id'],
            },
        ),
    ]
