# Generated by Django 6.1 on 2026-08-30 12:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_allowancebill_allowancebillline'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short stable identifier, e.g. EID_UL_FITR, EID_UL_ADHA', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('percentage_of_basic', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of basic salary paid as bonus, e.g. 100.00', max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bonus Type',
                'verbose_name_plural': 'Bonus Types',
                'db_table': 'bonus_types',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate used at generation time. Kept as a snapshot so changing the BonusType later does not rewrite past payslips.', max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_ta_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED. TA is paid on AllowanceBill; always 0 on new payrolls.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_tour_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED. Tour DA is paid on AllowanceBill; always 0 on new payrolls.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bonus_type',
            field=models.ForeignKey(blank=True, help_text='Set when this payroll was generated with a festival bonus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='hr.bonustype'),
        ),
    ]
