# Generated by Django 6.1 on 2026-09-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_seed_festival_bonus_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetarate',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_rates', to='hr.tacomponent'),
        ),
    ]
