# Generated by Django 6.1 on 2026-08-25 10:04

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.CharField(blank=True, help_text='Auto-generated unique code (e.g. DOC-0001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Doctor full name with title', max_length=255)),
                ('degrees', models.CharField(blank=True, help_text='e.g. MBBS, FCPS (Medicine)', max_length=255, null=True)),
                ('specialty', models.CharField(help_text='e.g. Cardiology, Medicine, Pediatrics, Dermatology', max_length=150)),
                ('bmdc_reg_number', models.CharField(blank=True, help_text='BM&DC Registration Number for statutory compliance', max_length=100, null=True)),
                ('chamber_or_hospital_name', models.CharField(help_text='Clinic, Chamber or Hospital Name', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Detailed chamber address', null=True)),
                ('territory_name', models.CharField(blank=True, help_text='Assigned sales territory', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('visiting_shift', models.CharField(choices=[('MORNING', 'Morning Shift'), ('EVENING', 'Evening Shift')], default='EVENING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketing_doctors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSampleDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_number', models.CharField(blank=True, help_text='Auto-generated distribution number (e.g. SMP-2026-0001)', max_length=50, unique=True)),
                ('distribution_date', models.DateField(default=datetime.date.today)),
                ('total_items_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Physician feedback / visit notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketing_doctor_sample_distributions',
                'ordering': ['-distribution_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSampleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, default='', help_text='Batch / Lot number of sample medicine for pharmacovigilance', max_length=100)),
                ('quantity', models.IntegerField(default=1, help_text='Number of sample units given')),
                ('unit', models.CharField(default='Strips', max_length=50)),
            ],
            options={
                'db_table': 'marketing_doctor_sample_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MPOClosingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_invoices_count', models.IntegerField(default=0)),
                ('total_receipts_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketing_mpo_closing_snapshots',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='ProductTargetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.IntegerField(default=1, help_text='Target units/boxes to sell')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-fetched from Product.selling_price as historical price snapshot', max_digits=12, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: target_quantity * unit_price', max_digits=14)),
            ],
            options={
                'db_table': 'product_target_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Descriptive title (e.g. 'August 2026 Monthly Sales Target')", max_length=255)),
                ('target_code', models.CharField(blank=True, help_text='Auto-generated unique code (e.g. TGT-2026-0001)', max_length=50, unique=True)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 Months)'), ('HALF_YEARLY', 'Half-Yearly (6 Months)'), ('YEARLY', 'Yearly / Annual'), ('CAMPAIGN', 'Special Campaign / Drive')], default='MONTHLY', max_length=50)),
                ('start_date', models.DateField(help_text='Campaign / Target start date')),
                ('end_date', models.DateField(help_text='Campaign / Target end date')),
                ('target_type', models.CharField(choices=[('AMOUNT_WISE', 'Amount-Wise Target'), ('PRODUCT_WISE', 'Product-Wise Target'), ('HYBRID', 'Hybrid (Amount & Product Targets)')], default='HYBRID', max_length=50)),
                ('total_target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total overall sales revenue target in BDT', max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / In-Progress'), ('ACHIEVED', 'Achieved'), ('MISSED', 'Missed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=50)),
                ('territory_name', models.CharField(blank=True, help_text='Assigned work area / territory', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Manager guidelines and campaign focus instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_targets',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
