# Generated by Django 6.1 on 2026-08-19 11:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Descriptive title (e.g. 'August 2026 Monthly Sales Target')", max_length=255)),
                ('target_code', models.CharField(blank=True, help_text='Auto-generated unique code (e.g. TGT-2026-0001)', max_length=50, unique=True)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 Months)'), ('HALF_YEARLY', 'Half-Yearly (6 Months)'), ('YEARLY', 'Yearly / Annual'), ('CAMPAIGN', 'Special Campaign / Drive')], default='MONTHLY', max_length=50)),
                ('start_date', models.DateField(help_text='Campaign / Target start date')),
                ('end_date', models.DateField(help_text='Campaign / Target end date')),
                ('target_type', models.CharField(choices=[('AMOUNT_WISE', 'Amount-Wise Target'), ('PRODUCT_WISE', 'Product-Wise Target'), ('HYBRID', 'Hybrid (Amount & Product Targets)')], default='HYBRID', max_length=50)),
                ('total_target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total overall sales revenue target in BDT', max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active / In-Progress'), ('ACHIEVED', 'Achieved'), ('MISSED', 'Missed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=50)),
                ('territory_name', models.CharField(blank=True, help_text='Assigned work area / territory', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Manager guidelines and campaign focus instructions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The Manager / Admin who created this target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_targets', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='The MPO / Marketing Staff assigned to this target', on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_targets',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTargetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_quantity', models.IntegerField(default=1, help_text='Target units/boxes to sell')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-fetched from Product.selling_price as historical price snapshot', max_digits=12, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: target_quantity * unit_price', max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_items', to='inventory.product')),
                ('sales_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='marketing.salestarget')),
            ],
            options={
                'db_table': 'product_target_items',
                'ordering': ['id'],
                'unique_together': {('sales_target', 'product')},
            },
        ),
    ]
