# Generated by Django 6.1 on 2026-08-24 09:02

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.CharField(blank=True, help_text='Auto-generated unique code (e.g. DOC-0001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Doctor full name with title', max_length=255)),
                ('degrees', models.CharField(blank=True, help_text='e.g. MBBS, FCPS (Medicine)', max_length=255, null=True)),
                ('specialty', models.CharField(help_text='e.g. Cardiology, Medicine, Pediatrics, Dermatology', max_length=150)),
                ('bmdc_reg_number', models.CharField(blank=True, help_text='BM&DC Registration Number for statutory compliance', max_length=100, null=True)),
                ('chamber_or_hospital_name', models.CharField(help_text='Clinic, Chamber or Hospital Name', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Detailed chamber address', null=True)),
                ('territory_name', models.CharField(blank=True, help_text='Assigned sales territory', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('visiting_shift', models.CharField(choices=[('MORNING', 'Morning Shift'), ('EVENING', 'Evening Shift'), ('BOTH', 'Both Shifts')], default='EVENING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_mpo', models.ForeignKey(blank=True, help_text='The MPO / Marketing Representative responsible for regular visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketing_doctors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSampleDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_number', models.CharField(blank=True, help_text='Auto-generated distribution number (e.g. SMP-2026-0001)', max_length=50, unique=True)),
                ('distribution_date', models.DateField(default=datetime.date.today)),
                ('total_items_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Physician feedback / visit notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor / Medical practitioner recipient', on_delete=django.db.models.deletion.PROTECT, related_name='sample_distributions', to='marketing.doctor')),
                ('mpo', models.ForeignKey(blank=True, help_text='The Marketing Officer who delivered the samples', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_samples', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(blank=True, help_text='Warehouse / Depot from which samples were drawn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_distributions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'marketing_doctor_sample_distributions',
                'ordering': ['-distribution_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSampleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, default='', help_text='Batch / Lot number of sample medicine for pharmacovigilance', max_length=100)),
                ('quantity', models.IntegerField(default=1, help_text='Number of sample units given')),
                ('unit', models.CharField(default='Strips', max_length=50)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.doctorsampledistribution')),
                ('product', models.ForeignKey(help_text='Sample medicine distributed', on_delete=django.db.models.deletion.PROTECT, related_name='distributed_samples', to='inventory.product')),
            ],
            options={
                'db_table': 'marketing_doctor_sample_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MPOClosingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_invoices_count', models.IntegerField(default=0)),
                ('total_receipts_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_mpo_closings', to=settings.AUTH_USER_MODEL)),
                ('mpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closing_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketing_mpo_closing_snapshots',
                'ordering': ['-year', '-month'],
                'unique_together': {('mpo', 'month', 'year')},
            },
        ),
    ]
