# Generated by Django 6.1 on 2026-08-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='assigned_mpo',
            field=models.ForeignKey(blank=True, help_text='The MPO / Marketing Representative responsible for regular visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorsampledistribution',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor / Medical practitioner recipient', on_delete=django.db.models.deletion.PROTECT, related_name='sample_distributions', to='marketing.doctor'),
        ),
        migrations.AddField(
            model_name='doctorsampledistribution',
            name='mpo',
            field=models.ForeignKey(blank=True, help_text='The Marketing Officer who delivered the samples', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_samples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorsampledistribution',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse / Depot from which samples were drawn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_distributions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='doctorsampleitem',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketing.doctorsampledistribution'),
        ),
        migrations.AddField(
            model_name='doctorsampleitem',
            name='product',
            field=models.ForeignKey(help_text='Sample medicine distributed', on_delete=django.db.models.deletion.PROTECT, related_name='distributed_samples', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='mpoclosingsnapshot',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_mpo_closings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mpoclosingsnapshot',
            name='mpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closing_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producttargetitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='The Manager / Admin who created this target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='assigned_to',
            field=models.ForeignKey(help_text='The MPO / Marketing Staff assigned to this target', on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producttargetitem',
            name='sales_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='marketing.salestarget'),
        ),
        migrations.AlterUniqueTogether(
            name='mpoclosingsnapshot',
            unique_together={('mpo', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='producttargetitem',
            unique_together={('sales_target', 'product')},
        ),
    ]
