# Generated by Django 6.1 on 2026-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_doctor_doctorsampledistribution_doctorsampleitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='visiting_shift',
            field=models.CharField(choices=[('MORNING', 'Morning Shift'), ('EVENING', 'Evening Shift')], default='EVENING', max_length=20),
        ),
    ]
