# Generated by Django 6.1 on 2026-09-01 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['-created_at'], name='stockmove_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'warehouse', '-created_at'], name='stockmove_prod_wh_date_idx'),
        ),
    ]
