# Generated by Django 6.1 on 2026-08-25 10:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. July 2026', max_length=100)),
                ('period_number', models.IntegerField(help_text='1 to 12 sequence within fiscal year')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting_periods',
                'ordering': ['fiscal_year', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gl_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unpresented_cheques_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('uncredited_deposits_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('adjusted_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECONCILED', 'Reconciled / Audited')], default='DRAFT', max_length=50)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounting_bank_reconciliations',
                'ordering': ['-statement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. FY 2026-2027', max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g. FY26-27', max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='Prevents back-dated postings')),
                ('is_closed', models.BooleanField(default=False, help_text='Year-end closed flag')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting_fiscal_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=1)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('party_type', models.CharField(blank=True, choices=[('CUSTOMER', 'Customer / Client'), ('SUPPLIER', 'Supplier / Vendor'), ('EMPLOYEE', 'Employee / Staff')], max_length=50, null=True)),
                ('party_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('foreign_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('foreign_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting_journal_entries',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('RECEIPT', 'Customer Collection (টাকা প্রাপ্তি)'), ('PAYMENT', 'Supplier / Vendor Payment (টাকা প্রদান)')], default='RECEIPT', max_length=50)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer / Client'), ('SUPPLIER', 'Supplier / Vendor'), ('EMPLOYEE', 'Employee / Staff')], default='CUSTOMER', max_length=50)),
                ('party_id', models.IntegerField(db_index=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(default='CASH', max_length=50)),
                ('reference_no', models.CharField(blank=True, help_text='TrxID / Cheque No / Slip No', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounting_payment_records',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('JOURNAL', 'Journal Voucher (JV)'), ('CONTRA', 'Contra Voucher (CV)'), ('PAYMENT', 'Payment Voucher (CPV/BPV)'), ('RECEIPT', 'Receipt Voucher (CRV/BRV)'), ('SALES_INVOICE', 'Sales Invoice Voucher (SIV)'), ('PURCHASE_BILL', 'Purchase Bill Voucher (PIV)'), ('PAYROLL', 'Payroll Disbursement Voucher (PYV)')], max_length=50)),
                ('voucher_date', models.DateField(db_index=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('POSTED', 'Posted / Committed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('source_module', models.CharField(blank=True, max_length=50, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_status', models.CharField(blank=True, choices=[('ISSUED', 'Issued / Received'), ('CLEARED', 'Cleared in Bank'), ('BOUNCED', 'Bounced / Dishonored'), ('CANCELLED', 'Cancelled')], max_length=50, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounting_vouchers',
                'ordering': ['-voucher_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset (সম্পদ)'), ('LIABILITY', 'Liability (দায়)'), ('EQUITY', 'Equity (মালিকানাস্বত্ব)'), ('REVENUE', 'Revenue (আয়/বিক্রয়)'), ('EXPENSE', 'Expense (ব্যয়/খরচ)')], max_length=50)),
                ('is_group', models.BooleanField(default=False, help_text='True if this is a header/folder, False if transactional leaf account')),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('is_reconciliation', models.BooleanField(default=False, help_text='Enabled for Cash/Bank reconciliation')),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=150, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_system_locked', models.BooleanField(default=False, help_text='Protects vital ERP accounts (AR, AP, Retained Earnings) from accidental deletion')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.accounthead')),
            ],
            options={
                'db_table': 'accounting_account_heads',
                'ordering': ['code'],
            },
        ),
    ]
