# Generated by Django 6.1 on 2026-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
