# Generated by Django 6.1 on 2026-09-01 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('sales', '0003_customerorder_cust_order_date_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payment_type', 'payment_date'], name='payrec_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['party_type', 'party_id'], name='payrec_party_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status', 'voucher_date'], name='voucher_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_type', 'voucher_date'], name='voucher_type_date_idx'),
        ),
    ]
