# Generated by Django 6.1 on 2026-08-25 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(help_text='Name of the pharmacy, hospital, clinic, or client business', max_length=255)),
                ('proprietor_name', models.CharField(blank=True, help_text='Name of the owner, proprietor, doctor, or primary contact person', max_length=255, null=True)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('drug_license_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('drug_license_expiry_date', models.DateField(blank=True, help_text='Expiry date of the DGDA drug license', null=True)),
                ('trade_license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.CharField(choices=[('RETAIL', 'Retail Pharmacy'), ('WHOLESALE', 'Wholesale Distributor'), ('HOSPITAL', 'Hospital / Clinic'), ('PRACTITIONER', 'Doctor / Practitioner'), ('INSTITUTION', 'Institution / NGO')], default='RETAIL', max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=50)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('MFS', 'bKash / Nagad / Rocket'), ('CREDIT', 'Credit (Due)')], default='CASH', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall order discount percentage, e.g. 5.00%', max_digits=5)),
                ('discount_flat', models.DecimalField(decimal_places=2, default=0.0, help_text='Flat cash discount amount in BDT', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('is_branch_booking', models.BooleanField(default=False, help_text='Designates whether this order is booked for fulfillment by another branch / depot')),
                ('booking_reference_number', models.CharField(blank=True, help_text='Inter-branch booking tracking code (e.g. BKG-2026-0001)', max_length=50, null=True)),
                ('booking_notes', models.TextField(blank=True, help_text='Special instructions for the destination branch dispatch team', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancelling or rejecting the order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'customer_order_items',
                'ordering': ['id'],
            },
        ),
    ]
