# Generated by Django 6.1 on 2026-08-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='booking_notes',
            field=models.TextField(blank=True, help_text='Special instructions for the destination branch dispatch team', null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='booking_reference_number',
            field=models.CharField(blank=True, help_text='Inter-branch booking tracking code (e.g. BKG-2026-0001)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_branch',
            field=models.ForeignKey(blank=True, help_text='Destination branch office / warehouse responsible for dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_booked_orders', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='is_branch_booking',
            field=models.BooleanField(default=False, help_text='Designates whether this order is booked for fulfillment by another branch / depot'),
        ),
    ]
