# Generated by Django 6.1 on 2026-08-25 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_branch',
            field=models.ForeignKey(blank=True, help_text='Destination branch office / warehouse responsible for dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_booked_orders', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.customerorder'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.warehouse'),
        ),
    ]
