# Generated by Django 6.1 on 2026-09-01 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_stockmove_created_idx_and_more'),
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['order_date', 'status'], name='cust_order_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['customer', 'order_date'], name='cust_order_cust_date_idx'),
        ),
    ]
